admin:
  hash: $2a$12$r3C0gKr1mMuNebKLFvbCdeSGwtaAx4O2XsIVx.4xy/g5LCJX4tq52
logstash:
  hash: $2a$12$r3C0gKr1mMuNebKLFvbCdeSGwtaAx4O2XsIVx.4xy/g5LCJX4tq52
kibanaserver:
  hash: $2a$12$r3C0gKr1mMuNebKLFvbCdeSGwtaAx4O2XsIVx.4xy/g5LCJX4tq52
kibanaro:
  hash: $2a$12$r3C0gKr1mMuNebKLFvbCdeSGwtaAx4O2XsIVx.4xy/g5LCJX4tq52
